# all placeholders are defaults
# if no placeholder is present, then the value is required
docker:
  # image of Dockerfile in main folder
  # you can either
  #   a. use prebuilt image from docker hub (https://hub.docker.com/r/cansucetin/strafe)
  #   b. use `strafe docker image build` command (cmd must be run under source code folder, or specify source code folder with flags)
  #      and build your own image.
  # if going with a, keep the image name same, you will pull my image.
  # if going with b, use image name `strafe` or something similar.
  image:
    name: cansucetin/strafe
    tag: latest
  socket: unix:///var/run/docker.sock
db:
  # postgres://user:password@ip:port/db?sslmode=disable
  url: 
s3:
  bucket: 
  account_id: 
  access_key_id:
  access_key_secret:
# random ascii art will be printed when help message is displayed
# no nsfw art, trust me.
display_ascii_art_on_help: true
